repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.5.2
    hooks:
      - id: stylua-github
  - repo: local
    hooks:
      - id: selene
        name: Selene
        entry: selene
        language: system
        types: [lua]
      - id: lua-language-server
        name: Lua Language Server
        entry: lua-language-server --check
        language: system
        types: [lua]
        pass_filenames: false
