-- Generate a Selene standard library for the Neovim API.
-- Run with the PINNED minimum-version binary, e.g.:
--   nvim --headless -u NONE -l scripts/generate-selene-std.lua neovim.yml
-- See AGENTS.md ("Selene standard policy") for the version ritual.
local raw_args = _G.arg or {}
local out_path = "neovim.yml"
for _, a in ipairs(raw_args) do
    if a ~= "--" then out_path = a end
end

local function selene_type(nvim_type)
    if nvim_type == "String" then return "string" end
    if nvim_type == "Integer" then return "number" end
    if nvim_type == "Boolean" then return "bool" end
    if nvim_type == "Function" then return "function" end
    if nvim_type == "Array" or nvim_type == "Dict" then return "table" end
    if nvim_type:find "ArrayOf" or nvim_type:find "DictOf" then return "table" end
    return "any"
end

local lines = {}
local function emit(indent, s) lines[#lines + 1] = string.rep("  ", indent) .. s end

emit(0, "# AUTO-GENERATED by scripts/generate-selene-std.lua. Do not edit.")
emit(0, "# Regenerate with the pinned minimum-version Neovim binary.")
emit(0, "globals:")

-- Full vim.api from embedded metadata. All args optional: the metadata does
-- not mark optionality, and required args would false-positive valid calls.
local info = vim.fn.api_info()
local funcs = {}
for _, f in ipairs(info.functions) do
    funcs[#funcs + 1] = f
end
table.sort(funcs, function(a, b) return a.name < b.name end)
for _, f in ipairs(funcs) do
    local short = "vim.api." .. f.name
    emit(1, short .. ":")
    if #(f.parameters or {}) == 0 then
        emit(2, "args: []")
    else
        emit(2, "args:")
        for _, param in ipairs(f.parameters) do
            emit(3, "- type: " .. selene_type(param[1]))
            emit(3, "  required: false")
        end
    end
    if f.deprecated_since ~= nil then
        emit(2, "deprecated:")
        emit(3, 'message: "' .. f.name .. " is deprecated since API level " .. f.deprecated_since .. '"')
    end
end

-- Core vim.* helpers used across the codebase. Loose signatures on purpose:
-- presence-checked, never arity-checked.
local helpers = {
    "vim.cmd",
    "vim.schedule",
    "vim.in_fast_event",
    "vim.notify",
    "vim.inspect",
    "vim.split",
    "vim.deepcopy",
    "vim.deep_equal",
    "vim.list_extend",
    "vim.tbl_contains",
    "vim.tbl_deep_extend",
    "vim.tbl_filter",
    "vim.tbl_map",
    "vim.uri_to_fname",
    "vim.system",
}
for _, name in ipairs(helpers) do
    emit(1, name .. ":")
    emit(2, "args:")
    emit(3, "- type: ...")
    emit(3, "  required: false")
end

-- Option/state scopes and nested namespaces: existence only.
for _, name in ipairs {
    "vim.b",
    "vim.bo",
    "vim.g",
    "vim.o",
    "vim.w",
    "vim.wo",
    "vim.t",
    "vim.v",
    "vim.env",
    "vim.opt",
    "vim.log",
    "vim.json",
    "vim.fs",
    "vim.ui",
} do
    emit(1, name .. ":")
    emit(2, "any: true")
end

-- Dynamic namespaces: too large to enumerate, checked for existence only.
-- vim.cmd is both callable and an index of Ex commands.
for _, name in ipairs { "vim.fn.*", "vim.uv.*", "vim.lsp.*", "vim.cmd.*" } do
    emit(1, name .. ":")
    emit(2, "any: true")
end

-- Busted-style test globals (no runtime dependency on Plenary).
for _, name in ipairs { "describe", "it" } do
    emit(1, name .. ":")
    emit(2, "args:")
    emit(3, "- type: string")
    emit(3, "- type: function")
end
emit(1, "before_each:")
emit(2, "args:")
emit(3, "- type: function")
-- Local test-harness helpers defined in tests/run.lua.
for _, name in ipairs { "check_equal", "check_same", "check_true" } do
    emit(1, name .. ":")
    emit(2, "args:")
    emit(3, "- type: ...")
    emit(3, "  required: false")
end

local fd = assert(io.open(out_path, "w"))
fd:write(table.concat(lines, "\n") .. "\n")
fd:close()
print("wrote " .. out_path .. " (" .. #funcs .. " api functions)")
