name: Lint

on: [push, pull_request]

jobs:
    lint:
        name: Selene
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup
              run: |
                  cargo install selene
            - name: Lint
              run: make lint
